#!/bin/bash
set -eu

urls() {
	local LIMIT=$1
	shift
	local TAGS=$*

	curl -fSsLG -d "limit=$LIMIT" -d "tags=$TAGS" http://konachan.com/post.xml 2> /dev/null |
		grep -o 'file_url="[^"]*"' | grep -o '//[^"]*' | sed -e 's/^/http:/'
}

if [ -z "${KONATAGS-}" ]; then
	KONATAGS="score:>=200"

	if [ "`hostname -s`" = "satorin" ]; then
		KONATAGS="$KONATAGS+nobody"
	fi
	if [ "`hostname -s`" = "shanghai" ]; then
		KONATAGS="$KONATAGS+rating:safe"
	fi
fi

TAGS="$KONATAGS+order:random+width:>=1600"

if [ -n "${SWAYSOCK-}" ]; then
	OUTPUTS=($(swaymsg -t get_outputs | jq -r .[].name))
	OUTPUT_I=0
	FILES=()
	for url in $(urls ${#OUTPUTS[@]} "$TAGS"); do
		file=$(mktemp)
		timeout 30 curl -fsSLo "$file" "$url"
		swaymsg output "${OUTPUTS[OUTPUT_I]}" background "$file" fill
		OUTPUT_I=$((OUTPUT_I + 1))
		FILES+=($file)
	done

	sleep 2

	# delete our temporary files
	# TODO: maybe use a cache directory that only gets cleaned up at the start
	for file in "${FILES[@]}"; do
		rm "$file"
	done
elif [ -n "${DISPLAY-}" ]; then
	SCREEN_COUNT=$(xrandr -q | grep ' connected' | wc -l)

	timeout 30 feh --no-fehbg --bg-fill $(urls "$SCREEN_COUNT" "$TAGS")
	xsetroot -cursor_name left_ptr
fi
