#!/bin/bash
shopt -s nullglob

build() {
  # add_full_dir does not follow symlinks, also allow masking
  for f in /usr/lib/modprobe.d/*.conf /etc/modprobe.d/*.conf; do
    add_file $f /etc/modprobe.d/$(basename "$f") 0644
  done
}
